/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author adeku
 */
public class FriendlyMode extends JFrame {

    String username;
    Client client;
    ClientThread ct;

    /**
     * Creates new form NewJFrame
     */
    public FriendlyMode(Client client, String username) {
        initComponents();
        this.client = client;
        this.username = username;

        ct = new ClientThread(this.client, this.username,ansA,ansB,ansC,ansD,ansF,messageBox,questionLabel,scoreCounter);
        ct.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ansGroup = new ButtonGroup();
        jScrollPane1 = new JScrollPane();
        messageBox = new JTextPane();
        jLabel1 = new JLabel();
        scoreCounter = new JLabel();
        questionLabel = new JLabel();
        ansA = new JRadioButton();
        ansB = new JRadioButton();
        ansC = new JRadioButton();
        ansD = new JRadioButton();
        ansF = new JRadioButton();
        submitButton = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trivia: Friendly Mode");

        messageBox.setEnabled(false);
        jScrollPane1.setViewportView(messageBox);

        jLabel1.setFont(new Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Score:");

        scoreCounter.setFont(new Font("Tahoma", 0, 48)); // NOI18N
        scoreCounter.setHorizontalAlignment(SwingConstants.CENTER);
        scoreCounter.setText("0");
        scoreCounter.setToolTipText("Your Current Score\n");

        questionLabel.setFont(new Font("Tahoma", 0, 16)); // NOI18N
        questionLabel.setText("Hello");

        ansGroup.add(ansA);
        ansA.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        ansA.setText("jRadioButton1");

        ansGroup.add(ansB);
        ansB.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        ansB.setText("jRadioButton2");

        ansGroup.add(ansC);
        ansC.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        ansC.setText("jRadioButton3");

        ansGroup.add(ansD);
        ansD.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        ansD.setText("jRadioButton4");

        ansGroup.add(ansF);
        ansF.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        ansF.setText("jRadioButton5");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(questionLabel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(scoreCounter, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(submitButton)
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(ansF)
                                .addComponent(ansD)
                                .addComponent(ansC)
                                .addComponent(ansB)
                                .addComponent(ansA)))
                        .addContainerGap(312, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scoreCounter, GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(questionLabel)
                .addGap(18, 18, 18)
                .addComponent(ansA)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ansB)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ansC)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ansD)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ansF)
                .addGap(18, 18, 18)
                .addComponent(submitButton, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private synchronized void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String answer = getChosenAnswer();
        client.sendToServer(answer);
    }//GEN-LAST:event_submitButtonActionPerformed

    private String getChosenAnswer() {
        if (ansA.isSelected()){
            return ansA.getText();
        }if (ansB.isSelected()){
            return ansB.getText();
        }if (ansC.isSelected()){
            return ansC.getText();
        }if (ansD.isSelected()){
            return ansD.getText();
        }if (ansF.isSelected()){
            return ansF.getText();
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JRadioButton ansA;
    private JRadioButton ansB;
    private JRadioButton ansC;
    private JRadioButton ansD;
    private JRadioButton ansF;
    private ButtonGroup ansGroup;
    private JLabel jLabel1;
    private JScrollPane jScrollPane1;
    private JTextPane messageBox;
    private JLabel questionLabel;
    private JLabel scoreCounter;
    private JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
