/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

/**
 * @author adeku
 */
public class GameMode extends javax.swing.JFrame {

    private Client client = new Client();
    private UserManager userManager = new UserManager();

    /**
     * Creates new form GameMode
     */

    public GameMode(String username) {
        initComponents();
        userManager.setUsername(username);

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectGameMode = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        startGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trivia: Choose Game Mode");
        setResizable(false);

        selectGameMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Practice Mode", "Friendly Mode", "Tournament Mode"}));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Please Choose a Game mode: ");

        startGame.setText("Start Game");
        startGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(startGame))
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectGameMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(selectGameMode, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(startGame)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void startGameActionPerformed(java.awt.event.ActionEvent evt) {
        client.connect();
        gameModeLaunch();
    }

    private void gameModeLaunch() {
        if (getGameMode().equals("Practice Mode")) {
            client.sendToServer(userManager.getUsername());
            client.sendToServer("GAME:PM");

            new PracticeMode(client, userManager.getUsername()).setVisible(true);
            this.dispose();
        }
        if (getGameMode().equals("Friendly Mode")) {
            client.sendToServer(userManager.getUsername());
            client.sendToServer("GM:FM");

            new FriendlyMode(client, userManager.getUsername()).setVisible(true);
            this.dispose();
        }
        if (getGameMode().equals("Tournament Mode")) {
            client.sendToServer(userManager.getUsername());
            client.sendToServer("GM:TM");

            new TournamentMode(client, userManager.getUsername()).setVisible(true);
            this.dispose();
        }
    }

    private String getGameMode() {
        String x = String.valueOf(selectGameMode.getSelectedItem());
        return x;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> selectGameMode;
    private javax.swing.JButton startGame;
    // End of variables declaration//GEN-END:variables
}
