/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import javax.swing.*;

/**
 * @author adeku
 */
public class PracticeMode extends javax.swing.JFrame {

    String username;
    Client client;
    ClientThread ct;


    /**
     * @param args the command line arguments
     */


    /**
     * Creates new form NewJFrame
     */
    public PracticeMode(Client client, String username) {
        initComponents();
        this.client = client;
        this.username = username;

        ct = new ClientThread(this.client, this.username, ansA, ansB, ansC, ansD, ansF, messageBox, questionLabel, scoreCounter);
        ct.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ansGroup = new javax.swing.ButtonGroup();
        JScrollPane jScrollPane1 = new JScrollPane();
        messageBox = new javax.swing.JTextPane();
        JLabel jLabel1 = new JLabel();
        scoreCounter = new javax.swing.JLabel();
        questionLabel = new javax.swing.JLabel();
        ansA = new javax.swing.JRadioButton();
        ansB = new javax.swing.JRadioButton();
        ansC = new javax.swing.JRadioButton();
        ansD = new javax.swing.JRadioButton();
        ansF = new javax.swing.JRadioButton();
        JButton submitButton = new JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trivia: Practice Mode");

        messageBox.setEnabled(false);
        jScrollPane1.setViewportView(messageBox);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Score:");

        scoreCounter.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        scoreCounter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreCounter.setText("0");
        scoreCounter.setToolTipText("Your Current Score\n");

        questionLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        questionLabel.setText("Hello");

        ansGroup.add(ansA);
        ansA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ansA.setText("jRadioButton1");

        ansGroup.add(ansB);
        ansB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ansB.setText("jRadioButton2");

        ansGroup.add(ansC);
        ansC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ansC.setText("jRadioButton3");

        ansGroup.add(ansD);
        ansD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ansD.setText("jRadioButton4");

        ansGroup.add(ansF);
        ansF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ansF.setText("jRadioButton5");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(questionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addComponent(scoreCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(21, 21, 21))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(submitButton)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(ansF)
                                                                .addComponent(ansD)
                                                                .addComponent(ansC)
                                                                .addComponent(ansB)
                                                                .addComponent(ansA)))
                                                .addContainerGap(312, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(scoreCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(questionLabel)
                                .addGap(18, 18, 18)
                                .addComponent(ansA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ansB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ansC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ansD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ansF)
                                .addGap(18, 18, 18)
                                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        client.sendToServer(getChosenAnswer());
    }//GEN-LAST:event_submitButtonActionPerformed

    //Getting radio button Text
    private String getChosenAnswer() {
        if (ansA.isSelected()){
            return ansA.getText();
        }if (ansB.isSelected()){
            return ansB.getText();
        }if (ansC.isSelected()){
            return ansC.getText();
        }if (ansD.isSelected()){
            return ansD.getText();
        }if (ansF.isSelected()){
            return ansF.getText();
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ansA;
    private javax.swing.JRadioButton ansB;
    private javax.swing.JRadioButton ansC;
    private javax.swing.JRadioButton ansD;
    private javax.swing.JRadioButton ansF;
    private javax.swing.ButtonGroup ansGroup;
    private javax.swing.JTextPane messageBox;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JLabel scoreCounter;
    // End of variables declaration//GEN-END:variables
}
