/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

/**
 *
 * @author adeku
 */
public class TournamentMode extends javax.swing.JFrame {

    String username;
    Client client;
    ClientThread ct;

    /**
     * Creates new form NewJFrame
     */
    public TournamentMode(Client client, String username) {
        initComponents();
        this.client = client;
        this.username = username;

        ct = new ClientThread(this.client, this.username,ansA,ansB,ansC,ansD,ansF,messageBox,questionLabel,scoreCounter);
        ct.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ansGroup = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        messageBox = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        scoreCounter = new javax.swing.JLabel();
        questionLabel = new javax.swing.JLabel();
        ansA = new javax.swing.JRadioButton();
        ansB = new javax.swing.JRadioButton();
        ansC = new javax.swing.JRadioButton();
        ansD = new javax.swing.JRadioButton();
        ansF = new javax.swing.JRadioButton();
        submitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trivia: Tournament Mode");

        messageBox.setEnabled(false);
        jScrollPane1.setViewportView(messageBox);
        jScrollPane1.getVerticalScrollBar().setValue(1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Score:");

        scoreCounter.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        scoreCounter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreCounter.setText("0");
        scoreCounter.setToolTipText("Your Current Score\n");

        questionLabel.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        questionLabel.setText("");

        ansGroup.add(ansA);
        ansA.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ansA.setText("");

        ansGroup.add(ansB);
        ansB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ansB.setText("");

        ansGroup.add(ansC);
        ansC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ansC.setText("");

        ansGroup.add(ansD);
        ansD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ansD.setText("");

        ansGroup.add(ansF);
        ansF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ansF.setText("");

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(questionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(scoreCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submitButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ansF)
                                .addComponent(ansD)
                                .addComponent(ansC)
                                .addComponent(ansB)
                                .addComponent(ansA)))
                        .addContainerGap(312, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scoreCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(questionLabel)
                .addGap(18, 18, 18)
                .addComponent(ansA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ansB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ansC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ansD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ansF)
                .addGap(18, 18, 18)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private synchronized void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String answer = getChosenAnswer();
        client.sendToServer(answer);
    }//GEN-LAST:event_submitButtonActionPerformed

    private String getChosenAnswer() {
        if (ansA.isSelected()){
            return ansA.getText();
        }if (ansB.isSelected()){
            return ansB.getText();
        }if (ansC.isSelected()){
            return ansC.getText();
        }if (ansD.isSelected()){
            return ansD.getText();
        }if (ansF.isSelected()){
            return ansF.getText();
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ansA;
    private javax.swing.JRadioButton ansB;
    private javax.swing.JRadioButton ansC;
    private javax.swing.JRadioButton ansD;
    private javax.swing.JRadioButton ansF;
    private javax.swing.ButtonGroup ansGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane messageBox;
    private javax.swing.JLabel questionLabel;
    private javax.swing.JLabel scoreCounter;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
